### ISSUE TITLE
Extract library from framework integration

### ISSUE THREAD

**Issue by tPl0ch** [M6Web/AmqpBundle#21]
Hi,
currently you can only use this with the full symfony framework, although it would also be usable within a silex or cilex or any other application.
Would it be possible to extract the implementation from the framework integration which would have an own package like `M6Web/amqp-core` or something like that?

Kind regards
Thomas

**Comment by omansour** [comment]
that's a good idea :+1:

**Comment by mente** [comment]
@omansour if you create a separate repository like `M6Web/amqp-core` then we can make an PR to both repos.

This way you keep rights of the package and we have core classes available :)

**Comment by iztoksvetik** [comment]
I have created a service provider for Silex using your bundle, i thought about extracting the core classes myself into a separate repo but then i would have to create a repo myself and it would not be under your namespace. So let me know when you extract the library and i can update the Provider with just the library as dependency not the entire bundle.

**Comment by omansour** [comment]
@mente I can do that :) https://github.com/M6Web/Amqp

**Comment by Tobion** [comment]
I think this issue can be closed considering silex is dead and the few classes it provides does not warrant a separate package. Also the things it brings are profiler integration and events and both are very tied to symfony.
You could also delete the repo https://github.com/M6Web/Amqp

**Comment by Oliboy50** [comment]
I agree with @Tobion  

we should delete the [M6Web/Amqp](https://github.com/M6Web/Amqp) repository (it's still empty since its creation 4 years ago)... IMHO, if we want to keep maintaining our open source repositories efficiently, we should decrease their number whenever possible... and this one seems to be a golden opportunity 🙏 

I don't have enough permissions to do so, so I'll leave @omansour doing it

anyway, I close this issue, feel free to open a new one if you think it's still relevant
